package top.zhkumanage.equip.entity;

public class EquipMSG {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_equip.id_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    private Integer idEquip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_equip.type_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    private String typeEquip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_equip.status_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    private Integer statusEquip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_equip.stroepath
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    private String stroepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_equip.idUser
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    private Integer iduser;

    private String message;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_equip.id_equip
     *
     * @return the value of message_equip.id_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public Integer getIdEquip() {
        return idEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_equip.id_equip
     *
     * @param idEquip the value for message_equip.id_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public void setIdEquip(Integer idEquip) {
        this.idEquip = idEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_equip.type_equip
     *
     * @return the value of message_equip.type_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public String getTypeEquip() {
        return typeEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_equip.type_equip
     *
     * @param typeEquip the value for message_equip.type_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public void setTypeEquip(String typeEquip) {
        this.typeEquip = typeEquip == null ? null : typeEquip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_equip.status_equip
     *
     * @return the value of message_equip.status_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public Integer getStatusEquip() {
        return statusEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_equip.status_equip
     *
     * @param statusEquip the value for message_equip.status_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public void setStatusEquip(Integer statusEquip) {
        this.statusEquip = statusEquip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_equip.stroepath
     *
     * @return the value of message_equip.stroepath
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public String getStroepath() {
        return stroepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_equip.stroepath
     *
     * @param stroepath the value for message_equip.stroepath
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public void setStroepath(String stroepath) {
        this.stroepath = stroepath == null ? null : stroepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_equip.idUser
     *
     * @return the value of message_equip.idUser
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_equip.idUser
     *
     * @param iduser the value for message_equip.idUser
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
}