package top.zhkumanage.user.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.idUser
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    private Integer iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userName
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.userPasswork
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    private String userpasswork;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.idUser
     *
     * @return the value of user_table.idUser
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.idUser
     *
     * @param iduser the value for user_table.idUser
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userName
     *
     * @return the value of user_table.userName
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userName
     *
     * @param username the value for user_table.userName
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.userPasswork
     *
     * @return the value of user_table.userPasswork
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public String getUserpasswork() {
        return userpasswork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.userPasswork
     *
     * @param userpasswork the value for user_table.userPasswork
     *
     * @mbggenerated Sun Apr 15 15:18:17 CST 2018
     */
    public void setUserpasswork(String userpasswork) {
        this.userpasswork = userpasswork == null ? null : userpasswork.trim();
    }
}