package top.zhkumanage.user.entity;

public class UserStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_status_table.idUser
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    private Integer iduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_status_table.status
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_status_table.idUser
     *
     * @return the value of user_status_table.idUser
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_status_table.idUser
     *
     * @param iduser the value for user_status_table.idUser
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_status_table.status
     *
     * @return the value of user_status_table.status
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_status_table.status
     *
     * @param status the value for user_status_table.status
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}