package top.zhkumanage.equip.dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import top.zhkumanage.equip.entity.EquipMSG;
@Repository
public interface EquipMSGMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    int deleteByPrimaryKey(Integer idEquip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    int insert(EquipMSG record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    EquipMSG selectByPrimaryKey(Integer idEquip);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    List<EquipMSG> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_equip
     *
     * @mbggenerated Tue Apr 17 11:07:14 CST 2018
     */
    int updateByPrimaryKey(EquipMSG record);

    List<EquipMSG> selectAllByUserId(Integer idUser);
}