package top.zhkumanage.user.dao;

import java.util.List;

import org.springframework.stereotype.Repository;
import top.zhkumanage.user.entity.UserStatus;

@Repository
public interface UserStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status_table
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    int deleteByPrimaryKey(Integer iduser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status_table
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    int insert(UserStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status_table
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    UserStatus selectByPrimaryKey(Integer iduser);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status_table
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    List<UserStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_status_table
     *
     * @mbggenerated Tue Apr 17 11:19:18 CST 2018
     */
    int updateByPrimaryKey(UserStatus record);
}